### PR TITLE
Add a health check subcommand.

### PR DESCRIPTION
**Pull request by fasaxc**
## Description

The change in #140 caused the health endpoint to only listen on localhost.  However, the kubelet checks the health explicitly using the pod IP (which is actually the host IP since typha is host networked) resulting in connection refused.

This change adds a subcommand to the typha executable that checks the health endpoint at `http://127.0.0.1:<port>` so that we can use a [liveness/readiness command](https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-probes/#define-a-liveness-command) instead of a HTTP check. I.e.

```
        livenessProbe:
          exec:
            command:
            - calico-typha
            - check
            - liveness
          periodSeconds: 30
          initialDelaySeconds: 30
        readinessProbe:
          exec:
            command:
            - calico-typha
            - check
            - readiness
          periodSeconds: 10
```

## Todos
- [x] Unit tests (full coverage)
- [x] Integration tests (delete as appropriate) In plan: Lance is adding a nightly k8s E2E run with typha.
- [x] Documentation
- [ ] ~Backport~
- [x] Release note

## Release Note

```release-note
Since Typha no longer exposes its readiness check on 0.0.0.0 (in order to improve security), our manifests have been updated to use a new command-line readiness check.
```

### CODE REVIEW

**Comment by neiljerram** [comment]
Not sure I understand the intent of the release note.  Does it mean

"For security, Typha no longer exposes its readiness check on 0.0.0.0, and our manifests have been updated to use a new command-line readiness check."

or

"For security, since Typha no longer exposes its readiness check on 0.0.0.0, our manifests have been updated to use a new command-line readiness check."

**Comment by fasaxc** [comment]
Well, the not exposing on 0.0.0.0 is for security.  The using a new command line readiness check is therefore required (because the old HTTP check relied on the health endpoint being exposed on 0.0.0.0).

**Comment by fasaxc** [comment]
Not a bad idea.

**Comment by neiljerram** [comment]
> Well, the not exposing on 0.0.0.0 is for security. The using a new command line readiness check is therefore required (because the old HTTP check relied on the health endpoint being exposed on 0.0.0.0).

I see that, but what do you want the release note here to cover?  If it's only *this* change, I think it would be clearer to say the sentence with "since" in.

On the other hand, if you're covering the previous change as well, because someone else forgot to, I think the first form is better.  Do you see what I mean?

**Pull request merged**
